export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const RETRIEVED_PRODUCT  = "RETRIEVED_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADDED_PRODUCT = "ADDED_PRODUCT";
export const DELETE_PRODUCT  ="DELETE_PRODUCT";
export const DELETED_PRODUCT = "DELETED_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATED_PRODUCT = "UPDATED_PRODUCT";